CREATE TABLE IF NOT EXISTS user_data(
uuid VARCHAR(36) PRIMARY KEY,
username VARCHAR(16) DEFAULT NULL,
first_doc BIGINT DEFAULT NULL,
denied_by VARCHAR(16) DEFAULT NULL,
deny_reason VARCHAR(300) DEFAULT NULL,
allowed_since VARCHAR(32) DEFAULT NULL,
allowed_by VARCHAR(16) DEFAULT NULL,
request_state BOOLEAN DEFAULT NULL,
last_seen BIGINT DEFAULT NULL,
online_hours INTEGER NOT NULL DEFAULT 0,
color VARCHAR(32) DEFAULT "<random>",
prefix VARCHAR(64) DEFAULT NULL,
voting INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS user_moderation (
uuid VARCHAR(36) PRIMARY KEY,
name VARCHAR(16) NOT NULL,
muted BOOLEAN NOT NULL DEFAULT FALSE,
banned BOOLEAN NOT NULL DEFAULT FALSE,
mute_reason VARCHAR(300) DEFAULT NULL,
ban_reason VARCHAR(300) DEFAULT NULL,
ban_performer VARCHAR(32) DEFAULT NULL,
mute_performer VARCHAR(32) DEFAULT NULL,
ban_expire BIGINT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS user_settings (
uuid VARCHAR(36) PRIMARY KEY,
name VARCHAR(16) NOT NULL,
afk BOOLEAN DEFAULT FALSE,
auto_afk BOOLEAN DEFAULT FALSE,
opt_chat BOOLEAN DEFAULT FALSE,
server_messages BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS username_history(
uuid VARCHAR(36),
username VARCHAR(16),
aufgenommen_am TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (uuid, username)
);

