groups:
  default:
    commands:
      - "me"
      - "msg"
    tabs:
      - "me"
      - "msg"
    erben-aus: [ ]
  spieler:
    commands:
      - "cmodify"
      - "playerinfo"
      - "prefix"
      - "tps"
      - "mail"
      - "mailbox"
      - "delmail"
      - "chatcolor"
      - "rbsuche"
    tabs:
      - "cmodify"
      - "playerinfo"
      - "prefix"
      - "tps"
      - "mail"
      - "mailbox"
      - "delmail"
      - "chatcolor"
      - "rbsuche"
    erben-aus:
      - "default"
  ModsPlus:
    commands:
      - "mute"
      - "request"
      - "kick"
      - "inv"
      - "oe"
      - "cinfo"
      - "tempban"
    erben-aus:
      - Spieler
  SuperMods:
    commands:
      - "ban"
      - "tp"
    erben-aus:
      - ModsPlus
  Developer:
    commands:
      - "inv"
      - "pl"
      - "version"
      - "reise"
    erben-aus:
      - Spieler