#Settings to Enable Plugin
prefix:
  length: 20 #Max Prefix length
  replaceChar: true #Replace "_" Char with " "
  coloredPrefix: true #Use Minecraft Formatting codes.
  remove: k
########------------------########
#Utilities
########------------------########
Utilities:
  firstJoinCommands:
    file: "firstjoincommands.txt"
  voteLinks:
    - "Link1 https://www.YourLink.eu"
    - "https://www.YourLink2.eu"
    - "https://www.YourLink3.eu"
  inHead: 10
  lootChest: true
  randomTP:
    center: "29 22 222"
    radius: 10000
  joinMessage: true
  leaveMessage: true
  dead-signs: true #Create Sign at Player Death Position
  playerGroup: Spieler #Default Player group for PermissionsEx
  kickNewbies: false
  colorChat: false #Chat color codes "&"
  tempban:
    time: 180 #time in Minutes
    kick_times: 5 #Amount of kicks from target before ban
  afk: #ALPHA use Carefully!
    autoAFK: true #Player gets AFK while IDLE on Server
    idleTime: 180 #Time in seconds player can Idle before AFK
########------------------########
#Discord Integration
########------------------########
discord:
  #Use Discord Web Hook to display chat to Discord
  default:
    enabled: false
    url: 'YourWebHook'
  #Use Discord Web Hook to display Errors in Discord
  error:
    enabled: false
    url: 'YourWebHook'
########------------------########
#Settings to Manage Warteschlange
########------------------########
warteschlange:
  maxPlayer: 15
  activeWorlds:
    - world
    - world_nether
    - world_the_end
########------------------########
# Join Message Modify
########------------------########
join:
  default-welcome-message: "&e{player} &eist zur端ckgekehrt!"
  groups:
    developer:
      message: "{player} &eist zur端ckgekehrt. &r&6Developer"
      container:
        - Mistergoody
#####################################
#Haupt Item Beschreibung
#####################################
item:
  lore: "COOLER_RASPI_COIN"
#####################################
#Einzelne Powers Einstellungen
#####################################
powers:
  fly:
    id: 1
    duration: 30
  night_vision:
    id: 2
    duration: 30
  haste:
    id: 3
    duration: 30
  #####################################
  #Einzelne Items Einstellungen
  #####################################
  items:
  sponge: #Super Sponge
    id: 1
    radius: 30
  knock: #Knockback Stick
    id: 1
    power: 100
    uses: 3
  mapLabel: #DynMap label addon
    type: STONE
    id: 1
loot: #Commands f端r Random Auswahl
  #CustomModelData: ist der wert der Wichtig ist f端r die einzelnen Items
  #DisplayName: Name des Items
  #Lore: Beschreibung von Item
  items:
    - "summon item %x% %y% %z% {Item:{id:\"minecraft:golden_apple\",count:1,components:{\"minecraft:max_stack_size\":1,\"minecraft:custom_name\":'{\"text\":\"Flug Item\"}',\"minecraft:custom_model_data\":1}}}" #Flug Item Beispiel
